// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9dgF1sW8aa09c6zCOVLzEtibiKm5csA',
    appId: '1:1047648611720:web:20f977e0862604343ede3d',
    messagingSenderId: '1047648611720',
    projectId: 'brainjamin-prod-app',
    authDomain: 'brainjamin-prod-app.firebaseapp.com',
    databaseURL: 'https://brainjamin-prod-app-default-rtdb.firebaseio.com',
    storageBucket: 'brainjamin-prod-app.firebasestorage.app',
    measurementId: 'G-PD98QX02V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6saAsaOW_99ETuA5V7kNvYS0hT_Fpa60',
    appId: '1:1047648611720:android:cbcf6e275652d3763ede3d',
    messagingSenderId: '1047648611720',
    projectId: 'brainjamin-prod-app',
    databaseURL: 'https://brainjamin-prod-app-default-rtdb.firebaseio.com',
    storageBucket: 'brainjamin-prod-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaMVayQJropR_bdZxguldNwVdHlWcVmI',
    appId: '1:1047648611720:ios:e4c12f514bd8b5ca3ede3d',
    messagingSenderId: '1047648611720',
    projectId: 'brainjamin-prod-app',
    databaseURL: 'https://brainjamin-prod-app-default-rtdb.firebaseio.com',
    storageBucket: 'brainjamin-prod-app.firebasestorage.app',
    androidClientId: '1047648611720-rg02qsmh0robo5tie2fn15qhm3kfnu89.apps.googleusercontent.com',
    iosClientId: '1047648611720-36o7lult2k7iob1f397q89tn1puesm08.apps.googleusercontent.com',
    iosBundleId: 'com.stratech.brainjamin',
  );

}